# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               El blog de Lucy
tagline:             'El blog de Lu'
description:         'Un blog'
url:                 https://lucia15.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Lucía
#  url:               https://twitter.com/lucy
#  email:             bla@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
